### PR TITLE
Manually migrate for osx-arm64, bump to v2.0.2

### PR DESCRIPTION
**Pull request by corneliusroemer**
No PR is opened because the optional dependency python-isal isn't built for arm yet

We can just disable that optional dep for arm64 and things should work still

osx-arm64 errors with `Bad CPU type in executable`

```
2024-07-11T14:27:43.6961810Z /Users/runner/miniforge3/conda-bld/xopen_1720707760584/work/conda_build.sh: line 4: /Users/runner/miniforge3/conda-bld/xopen_1720707760584/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python: Bad CPU type in executable
```

https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/975849/logs/160

### CODE REVIEW

**Comment by corneliusroemer** [comment]
@conda-forge-admin, please rerender

**Comment by rhpvorderman** [comment]
What the hell is this?! You added yourself as maintainer and just merged it without even notifying me or @marcelm? What is this all about? Is this a new conda-forge policy? 

I respect that macos-arm64 is an important platform and that action is necessary, but I'd rather stay in the loop rather than be shoved to the side. I can see that sometimes direct action from upper conda-forge management is needed if maintainers are unresponsive, but this was just 4 hours between the PR opening and it being merged.

**Comment by rhpvorderman** [comment]
I deeply apologize for my rant. I have misread the chain of events.

**Comment by rhpvorderman** [comment]
Thanks for all the help @corneliusroemer . I only saw that you were added as  maintainer after I saw this. I was bit baffled. Again I apologize for the above post. I deleted it in shame.

**Comment by corneliusroemer** [comment]
Hey @rhpvorderman no worries whatsoever, I don't think there's anything to be ashamed of 😀 thanks for all your work around python-isa-l etc!

**Pull request merged**
