### PR TITLE
Attempt to make the package noarch: python

### PR DESCRIPTION
**Pull request by marcelm**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marcelm** [comment]
@conda-forge-admin, please rerender

**Comment by marcelm** [comment]
Seems to work, only problem I can see is that the build string is identical for all packages (all files are named `xopen-2.0.0-pyhd8ed1ab_1.conda`).

**Comment by rhpvorderman** [comment]
> packages can't have selectors. If the selectors are necessary, please remove noarch: python.

I am affraid they are necessary, right? I don't want biocontainers without python-isal...

**Comment by marcelm** [comment]
I think the warning is just incorrect and can maybe be ignored.

**Comment by rhpvorderman** [comment]
I trust your judgement in this case. The worst case scenario is that we need to rollback the change, so I vote to go ahead.
Can this be based on the 2.0.1 release? So we do not accidentally get another broken package out?

**Comment by marcelm** [comment]
@conda-forge-admin, please rerender

**Comment by rhpvorderman** [comment]
Superseded by #47

**Pull request closed without merging**
