### PR TITLE
Also require ISA-L on macos

### PR DESCRIPTION
**Pull request by rhpvorderman**
ISA-L has recently become available on MacOS via conda. It was some work but it was doable. Windows though... It really is a third-class citizen when it comes to building software to get your work done. I am working on that in my spare time, as it has no relevance to my work (we use linux exclusively) whatsoever. At least also mac is supported now. So most of the developer crowd should be on board.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rhpvorderman** [comment]
No rerender was needed according to the latest version of conda-smithy.

**Comment by marcelm** [comment]
Let me fix the URLs while we’re bumping the build number anyway.

**Comment by rhpvorderman** [comment]
Looking good! I see we doubled the bus factor for two projects today :+1:. Hopefully other interested people join as well at some point.

**Comment by marcelm** [comment]
Exactly, the bus factor is what I thought about as well :smile:

**Pull request merged**
