### PR TITLE
xopen v0.8.4

### PR DESCRIPTION
**Pull request by rhpvorderman**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Retry from autotick.

### CODE REVIEW

**Comment by rhpvorderman** [comment]
Strange. I can merge it on my own PC into master. Why does the merging not work all of a sudden?

**Comment by marcelm** [comment]
I think we are not supposed to use branches on the main feedstock repo for PRs. It seems you [just published version 0.8.4 to anaconda.org](https://anaconda.org/conda-forge/xopen/) already ...

Oh well, no harm done ... Should we just merge this now? Or will that trigger another deploy?

**Comment by rhpvorderman** [comment]
> **I think we are not supposed to use branches on the main feedstock repo for PRs. It seems you just published version 0.8.4 to anaconda.org already ...**

Whoops! Did not realize that. Sorry!

> Oh well, no harm done ... Should we just merge this now? Or will that trigger another deploy?

I think it won't build unless the build number has changed right? 
I will merge so master is correct. If anything breaks I will make a new PR with an increased build number.

**Comment by rhpvorderman** [comment]
I just realized that it might have autobuild because I had the keyword `release` in the branch name.

**Comment by marcelm** [comment]
I think "release" in the branch name does not matter if I interpret [the docs](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests) correctly.

**Comment by rhpvorderman** [comment]
Thanks. Next time I will open a separate branch on my own fork.

**Pull request merged**
