### PR TITLE
Require version of igzip that works with concatenated gzip files

### PR DESCRIPTION
**Pull request by rhpvorderman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rhpvorderman** [comment]
@conda-forge-admin, please rerender

**Comment by marcelm** [comment]
Thanks for the change! Of course I approve, but why did you request a review at all?

**Comment by rhpvorderman** [comment]
I didn't... I think conda-forge does so automatically? I just posted to link to make sure you were notified. I mean, a little version jump to a "not-bugged" version of a dependency does not warrant a full review in my opinion. Best to get it merged as soon as possible.

**Comment by marcelm** [comment]
Ah that explains it. Weird that it looks as if you did. But no worries about the merge itself, I would also have merged this without any approval.

**Comment by marcelm** [comment]
Ah, I learned something, from https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners:
> Code owners are automatically requested for review when someone opens a pull request that modifies code that they own.

**Comment by rhpvorderman** [comment]
Does "owning" code make sense in the context of an *Open Source* code *sharing* platform? I guess "code parent" is more appropriate. No matter how much you love your code, as soon as it is open source it will start leading a life of its own. (And regardless, you will worry about it for the rest of your life :wink: ).

**Pull request merged**
