### PR TITLE
Add isa-l as a dependency to enable fast compression and decompression.

### PR DESCRIPTION
**Pull request by rhpvorderman**
Since the release of isa-l 2.30.0 igzip should also be able to decompress concatenated gzip.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rhpvorderman** [comment]
@conda-forge-admin, please rerender

**Comment by marcelm** [comment]
I think if we do this, then we should als add `pigz` as dependency as well (see #3) and then add a sentence or two to the projects README suggesting something like "for best experience, please run `apt install isal pigz`".

**Review by marcelm — CHANGES_REQUESTED** [review]
Hm, shouldn’t there be a merge conflict now that master is at 1.0.1? Anyway, I think I’m fine with this. Can you please
- Rebase on top of master
- Add the `pigz` dependency
- And remove the `bz2file` dependency while you’re at it?

**Comment by rhpvorderman** [comment]
Yes I agree. pigz and isal bring themselves no extra dependencies (zlib is already there for python). So I think we can add them. Especially since compiled binaries will be delivered by conda.

**Comment by rhpvorderman** [comment]
@marcelm. Ah simultaneous :wink:. On it!

**Comment by rhpvorderman** [comment]
@marcelm. I see conda builds a python build for every version of python. That should not be necessary right? It is a pure python package.

**Comment by marcelm** [comment]
Yes, I think it needs to be `noarch: python`

**Comment by marcelm** [comment]
Ah, there’s a bot command for that:

@conda-forge-admin, please add noarch: python

**Comment by marcelm** [comment]
`# [linux]`  is in the run section, so I think we need to drop the `noarch`.

**Comment by rhpvorderman** [comment]
@marcelm. Alternatively I could make isa-l compile on windows and mac as well, then the selector can be removed.. The build instructions are available on the isa-l github page.

I tried mac already. But unfortunately it is not similar to linux and I cannot debug it since I do not own a mac. I do own a windows copy though. So I could make windows work. This PR will have to wait a little longer but the benefits will reach more people.

**Comment by marcelm** [comment]
I realize now that using `noarch` isn’t the correct thing no matter what since isa-l is x86-only.

There’s for example [the effort to provide conda-forge packages for the new ARM macOS](https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/), so we will need selectors anyway.

Of course it would still be cool if you could get isa-l to compile on more platforms, but you shouldn’t do it to just to leave the `noarch` in this recipe.

It feels a bit of a waste to create so many nearly identical packages just because the dependencies are different between architectures, but that’s how it has to be with the current Conda packaging format.

**Comment by rhpvorderman** [comment]
> I realize now that using noarch isn’t the correct thing no matter what since isa-l is x86-only.

No it isn't. ARM instructions are also provided. But I can't test that.

> Of course it would still be cool if you could get isa-l to compile on more platforms, but you shouldn’t do it to just to leave the noarch in this recipe.

Yes, Indeed, well I guess we should remove the noarch then. Is there a command for that?

**Comment by rhpvorderman** [comment]
> It feels a bit of a waste to create so many nearly identical packages just because the dependencies are different between architectures, but that’s how it has to be with the current Conda packaging format.

Yes. But I think it will be better now that the dependencies are listed as build dependencies, not host dependencies. Let me check.

**Comment by rhpvorderman** [comment]
@conda-forge-admin, please rerender

**Review by marcelm — APPROVED** [review]

**Comment by marcelm** [comment]
Sorry about editing your comment, that was completely unintentional.

I’ll just merge this now.

**Pull request merged**
